services:
  asr-paraformer:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-asr-paraformer:latest
    container_name: asr-paraformer
    ports:
      - "27003:8000"
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped

  asr-sensevoice:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-asr-sensevoice:latest
    container_name: asr-sensevoice
    ports:
      - "27103:8000"
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped

  diar:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-diar-default:latest
    container_name: diar
    ports:
      - "27004:8000"
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped
