services:
  f5tts:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-tts-f5:latest
    container_name: f5tts
    expose:
      - "8999"
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped

  cosyvoice:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-tts-cosyvoice:latest
    container_name: cosyvoice
    ports:
      - "27005:8000"
    volumes:
      - /root/vv/LunaModels/tts/prompts:/prompts
    # command: sleep inf
    environment:
      F5TTS_URL: "http://f5tts:8999/tts"
    depends_on:
      - f5tts
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped

  vad:
    image: lunalabs-cn-shanghai.cr.volces.com/luna/luna-agent-vad-silero:latest
    container_name: vad
    ports:
      - "27002:8000"
    environment:
      VAD_POOL_SIZZE: 10
      MIN_SILENCE_DURATION_MS: 300
      SPEECH_PAD_MS: 100
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    restart: unless-stopped
